code --install-extension formulahendry.code-runner
code --install-extension formulahendry.vscode-mysql
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension ikuyadeu.r-pack
code --install-extension james-yu.latex-workshop
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode.powershell
code --install-extension pkief.material-icon-theme
code --install-extension rdebugger.r-debugger
code --install-extension reditorsupport.r
code --install-extension yzhang.markdown-all-in-one
